// AUTO-GENERATED by scripts/generate-types.js — do not edit manually.
// Re-run: node scripts/generate-types.js
// Generated: 2026-03-23  |  Source: src-tauri/src/main.rs
// 145 commands exported.

/// Tauri invoke() with full type safety for all FrostFinder commands.
declare function invoke<T = unknown>(cmd: TauriCommand, args?: Record<string, unknown>): Promise<T>;

type TauriCommand =
  | 'check_optional_deps'
  | 'get_platform'
  | 'set_ql_payload'
  | 'get_ql_payload'
  | 'preload_dir'
  | 'list_directory_fast'
  | 'get_entry_meta'
  | 'list_directory_chunk'
  | 'list_directory_full_streamed'
  | 'list_directory'
  | 'get_home_dir'
  | 'get_sidebar_data'
  | 'get_drives'
  | 'mount_drive'
  | 'unlock_and_mount_encrypted'
  | 'open_file'
  | 'get_file_preview'
  | 'read_text_file'
  | 'write_text_file'
  | 'get_thumbnail'
  | 'get_thumbnail_bytes'
  | 'get_thumbnail_bytes_batch'
  | 'empty_trash'
  | 'empty_trash_stream'
  | 'batch_thumbnails'
  | 'get_thumbnail_url_batch'
  | 'gc_thumbnail_cache'
  | 'open_as_root'
  | 'check_permission'
  | 'rename_file'
  | 'batch_rename'
  | 'get_office_preview'
  | 'delete_file'
  | 'secure_delete'
  | 'find_duplicates'
  | 'delete_items_stream'
  | 'install_font'
  | 'is_font_installed'
  | 'create_directory'
  | 'create_file_cmd'
  | 'get_dir_size'
  | 'get_dir_size_fast'
  | 'copy_file'
  | 'move_file'
  | 'create_new_document'
  | 'cancel_file_op'
  | 'copy_files_batch'
  | 'move_files_batch'
  | 'parse_dropped_paths'
  | 'compress_files'
  | 'get_archive_contents'
  | 'extract_archive'
  | 'delete_items'
  | 'list_apps_for_file'
  | 'open_with_app'
  | 'open_terminal'
  | 'open_in_editor'
  | 'window_minimize'
  | 'window_maximize'
  | 'window_close'
  | 'window_set_fullscreen'
  | 'window_is_maximized'
  | 'get_native_window_handle'
  | 'mpv_open_external'
  | 'mpv_is_running'
  | 'diff_files'
  | 'eject_drive'
  | 'get_media_port'
  | 'read_svg_icon'
  | 'mount_iso'
  | 'unmount_iso'
  | 'get_iso_loop_device'
  | 'mount_smb'
  | 'unmount_smb'
  | 'get_smb_mounts'
  | 'list_smb_shares'
  | 'list_usb_drives'
  | 'write_iso_to_usb'
  | 'mount_dmg'
  | 'unmount_dmg'
  | 'get_dmg_loop_device'
  | 'mount_webdav'
  | 'unmount_cloud'
  | 'get_cloud_mounts'
  | 'scan_icon_folder'
  | 'check_rclone'
  | 'list_rclone_remotes'
  | 'add_cloud_provider'
  | 'mount_cloud_provider'
  | 'unmount_cloud_provider'
  | 'remove_cloud_provider'
  | 'restore_cloud_mounts'
  | 'find_git_root'
  | 'get_git_status'
  | 'invalidate_git_cache'
  | 'check_gocryptfs'
  | 'list_vaults'
  | 'create_vault'
  | 'unlock_vault'
  | 'lock_vault'
  | 'remove_vault'
  | 'watch_dir'
  | 'unwatch_dir'
  | 'get_watch_mode'
  | 'append_error_log'
  | 'get_error_log'
  | 'clear_error_log'
  | 'get_file_checksums'
  | 'get_file_meta_exif'
  | 'write_file_meta_exif'
  | 'get_audio_tags'
  | 'write_audio_tags'
  | 'get_exif_tags'
  | 'write_exif_tags'
  | 'get_pdf_meta'
  | 'write_pdf_meta'
  | 'compare_dirs'
  | 'mount_sftp'
  | 'unmount_sftp'
  | 'get_sftp_mounts'
  | 'mount_ftp'
  | 'unmount_ftp'
  | 'get_ftp_mounts'
  | 'get_file_permissions'
  | 'chmod_entry'
  | 'chown_entry'
  | 'open_new_window'
  | 'scan_dir_sizes'
  | 'probe_video_codec'
  | 'load_plugins'
  | 'save_plugins'
  | 'check_plugin_trust'
  | 'approve_plugin'
  | 'revoke_plugin_trust'
  | 'run_plugin_command'
  | 'save_undo_history'
  | 'load_undo_history'
  | 'clear_undo_history'
  | 'get_cloud_sync_state'
  | 'check_cloud_remote_reachable'
  | 'start_rclone_rc'
  | 'stop_rclone_rc'
  | 'rclone_rc_list'
  | 'rclone_rc_copy'
  | 'detect_mtp_devices'
  | 'mount_mtp'
  | 'unmount_mtp'
  | 'get_settings'
  | 'set_settings';

// ── Per-command typed invoke overloads ───────────────────────────────────────

/** invoke('check_optional_deps') */
declare function invoke(cmd: 'check_optional_deps', args?: never): Promise<unknown /* std::collections::HashMap<String, bool> */>;

/** invoke('get_platform') */
declare function invoke(cmd: 'get_platform', args?: never): Promise<string>;

/** invoke('set_ql_payload') */
declare function invoke(cmd: 'set_ql_payload', args: { payload: string }): Promise<void>;

/** invoke('get_ql_payload') */
declare function invoke(cmd: 'get_ql_payload', args?: never): Promise<string>;

/** invoke('preload_dir') */
declare function invoke(cmd: 'preload_dir', args: { path: string }): Promise<void>;

/** invoke('list_directory_fast') */
declare function invoke(cmd: 'list_directory_fast', args: { path: string }): Promise<unknown /* DirectoryListingFast */>;

/** invoke('get_entry_meta') */
declare function invoke(cmd: 'get_entry_meta', args: { path: string }): Promise<unknown /* FileEntry */ | null>;

/** invoke('list_directory_chunk') */
declare function invoke(cmd: 'list_directory_chunk', args: { paths: string[] }): Promise<unknown /* FileEntry */[]>;

/** invoke('list_directory_full_streamed') */
declare function invoke(cmd: 'list_directory_full_streamed', args: { path: string, request_id: number }): Promise<void>;

/** invoke('list_directory') */
declare function invoke(cmd: 'list_directory', args: { path: string }): Promise<unknown /* DirectoryListing */>;

/** invoke('get_home_dir') */
declare function invoke(cmd: 'get_home_dir', args?: never): Promise<string>;

/** invoke('get_sidebar_data') */
declare function invoke(cmd: 'get_sidebar_data', args?: never): Promise<unknown /* SidebarData */>;

/** invoke('get_drives') */
declare function invoke(cmd: 'get_drives', args?: never): Promise<unknown /* DriveInfo */[]>;

/** invoke('mount_drive') */
declare function invoke(cmd: 'mount_drive', args: { device: string }): Promise<string>;

/** invoke('unlock_and_mount_encrypted') */
declare function invoke(cmd: 'unlock_and_mount_encrypted', args: { device: string, passphrase: string }): Promise<string>;

/** invoke('open_file') */
declare function invoke(cmd: 'open_file', args: { path: string }): Promise<void>;

/** invoke('get_file_preview') */
declare function invoke(cmd: 'get_file_preview', args: { path: string }): Promise<unknown /* FilePreview */>;

/** invoke('read_text_file') */
declare function invoke(cmd: 'read_text_file', args: { path: string }): Promise<string>;

/** invoke('write_text_file') */
declare function invoke(cmd: 'write_text_file', args: { path: string, content: string }): Promise<void>;

/** invoke('get_thumbnail') */
declare function invoke(cmd: 'get_thumbnail', args: { path: string }): Promise<string>;

/** invoke('get_thumbnail_bytes') */
declare function invoke(cmd: 'get_thumbnail_bytes', args: { path: string }): Promise<number[]>;

/** invoke('get_thumbnail_bytes_batch') */
declare function invoke(cmd: 'get_thumbnail_bytes_batch', args: { paths: string[] }): Promise<string[]>;

/** invoke('empty_trash') */
declare function invoke(cmd: 'empty_trash', args?: never): Promise<number>;

/** invoke('empty_trash_stream') */
declare function invoke(cmd: 'empty_trash_stream', args?: never): Promise<number>;

/** invoke('batch_thumbnails') */
declare function invoke(cmd: 'batch_thumbnails', args: { paths: string[] }): Promise<string[]>;

/** invoke('get_thumbnail_url_batch') */
declare function invoke(cmd: 'get_thumbnail_url_batch', args: { paths: string[] }): Promise<string[]>;

/** invoke('gc_thumbnail_cache') */
declare function invoke(cmd: 'gc_thumbnail_cache', args?: never): Promise<number>;

/** invoke('open_as_root') */
declare function invoke(cmd: 'open_as_root', args: { path: string }): Promise<void>;

/** invoke('check_permission') */
declare function invoke(cmd: 'check_permission', args: { path: string }): Promise<boolean>;

/** invoke('rename_file') */
declare function invoke(cmd: 'rename_file', args: { old_path: string, new_name: string }): Promise<string>;

/** invoke('batch_rename') */
declare function invoke(cmd: 'batch_rename', args: { paths: string[], options: unknown /* BatchRenameOptions */ }): Promise<string[]>;

/** invoke('get_office_preview') */
declare function invoke(cmd: 'get_office_preview', args: { path: string }): Promise<unknown>;

/** invoke('delete_file') */
declare function invoke(cmd: 'delete_file', args: { path: string, trash: boolean }): Promise<void>;

/** invoke('secure_delete') */
declare function invoke(cmd: 'secure_delete', args: { paths: string[], passes: number }): Promise<void>;

/** invoke('find_duplicates') */
declare function invoke(cmd: 'find_duplicates', args: { root_path: string, recursive: boolean }): Promise<string[][]>;

/** invoke('delete_items_stream') */
declare function invoke(cmd: 'delete_items_stream', args: { paths: string[], trash: boolean }): Promise<void>;

/** invoke('install_font') */
declare function invoke(cmd: 'install_font', args: { path: string }): Promise<string>;

/** invoke('is_font_installed') */
declare function invoke(cmd: 'is_font_installed', args: { filename: string }): Promise<boolean>;

/** invoke('create_directory') */
declare function invoke(cmd: 'create_directory', args: { path: string, name: string }): Promise<string>;

/** invoke('create_file_cmd') */
declare function invoke(cmd: 'create_file_cmd', args: { path: string, name: string }): Promise<string>;

/** invoke('get_dir_size') */
declare function invoke(cmd: 'get_dir_size', args: { path: string }): Promise<number>;

/** invoke('get_dir_size_fast') */
declare function invoke(cmd: 'get_dir_size_fast', args: { path: string }): Promise<number>;

/** invoke('copy_file') */
declare function invoke(cmd: 'copy_file', args: { src: string, dest_dir: string }): Promise<string>;

/** invoke('move_file') */
declare function invoke(cmd: 'move_file', args: { src: string, dest_dir: string }): Promise<string>;

/** invoke('create_new_document') */
declare function invoke(cmd: 'create_new_document', args: { path: string, name: string, doc_type: string }): Promise<string>;

/** invoke('cancel_file_op') */
declare function invoke(cmd: 'cancel_file_op', args?: never): Promise<void>;

/** invoke('copy_files_batch') */
declare function invoke(cmd: 'copy_files_batch', args: { srcs: string[], dest_dir: string }): Promise<void>;

/** invoke('move_files_batch') */
declare function invoke(cmd: 'move_files_batch', args: { srcs: string[], dest_dir: string }): Promise<void>;

/** invoke('parse_dropped_paths') */
declare function invoke(cmd: 'parse_dropped_paths', args: { uri_list: string }): Promise<string[]>;

/** invoke('compress_files') */
declare function invoke(cmd: 'compress_files', args: { paths: string[], output_path: string, compression_level: number | null, password?: string }): Promise<unknown /* CompressResult */>;

/** invoke('get_archive_contents') */
declare function invoke(cmd: 'get_archive_contents', args: { path: string }): Promise<unknown /* ArchiveItem */[]>;

/** invoke('extract_archive') */
declare function invoke(cmd: 'extract_archive', args: { archive_path: string, dest_dir: string }): Promise<number>;

/** invoke('delete_items') */
declare function invoke(cmd: 'delete_items', args: { paths: string[] }): Promise<void>;

/** invoke('list_apps_for_file') */
declare function invoke(cmd: 'list_apps_for_file', args: { _path: string }): Promise<unknown /* AppEntry */[]>;

/** invoke('open_with_app') */
declare function invoke(cmd: 'open_with_app', args: { path: string, exec: string }): Promise<void>;

/** invoke('open_terminal') */
declare function invoke(cmd: 'open_terminal', args: { path: string }): Promise<void>;

/** invoke('open_in_editor') */
declare function invoke(cmd: 'open_in_editor', args: { path: string }): Promise<void>;

/** invoke('window_minimize') */
declare function invoke(cmd: 'window_minimize', args?: never): Promise<void>;

/** invoke('window_maximize') */
declare function invoke(cmd: 'window_maximize', args?: never): Promise<boolean>;

/** invoke('window_close') */
declare function invoke(cmd: 'window_close', args?: never): Promise<void>;

/** invoke('window_set_fullscreen') */
declare function invoke(cmd: 'window_set_fullscreen', args: { fullscreen: boolean }): Promise<void>;

/** invoke('window_is_maximized') */
declare function invoke(cmd: 'window_is_maximized', args?: never): Promise<boolean>;

/** invoke('get_native_window_handle') */
declare function invoke(cmd: 'get_native_window_handle', args?: never): Promise<unknown /* NativeWindowHandle */>;

/** invoke('mpv_open_external') */
declare function invoke(cmd: 'mpv_open_external', args: { path: string, start_time: number | null, fullscreen: boolean | null }): Promise<void>;

/** invoke('mpv_is_running') */
declare function invoke(cmd: 'mpv_is_running', args?: never): Promise<boolean>;

/** invoke('diff_files') */
declare function invoke(cmd: 'diff_files', args: { path_a: string, path_b: string }): Promise<unknown /* DiffResult */>;

/** invoke('eject_drive') */
declare function invoke(cmd: 'eject_drive', args: { mountpoint: string, device: string }): Promise<void>;

/** invoke('get_media_port') */
declare function invoke(cmd: 'get_media_port', args?: never): Promise<number>;

/** invoke('read_svg_icon') */
declare function invoke(cmd: 'read_svg_icon', args: { path: string }): Promise<string>;

/** invoke('mount_iso') */
declare function invoke(cmd: 'mount_iso', args: { path: string }): Promise<string>;

/** invoke('unmount_iso') */
declare function invoke(cmd: 'unmount_iso', args: { loop_dev: string }): Promise<void>;

/** invoke('get_iso_loop_device') */
declare function invoke(cmd: 'get_iso_loop_device', args: { iso_path: string }): Promise<string>;

/** invoke('mount_smb') */
declare function invoke(cmd: 'mount_smb', args: { server: string, share: string, username: string | null, password: string | null }): Promise<string>;

/** invoke('unmount_smb') */
declare function invoke(cmd: 'unmount_smb', args: { server: string, share: string }): Promise<void>;

/** invoke('get_smb_mounts') */
declare function invoke(cmd: 'get_smb_mounts', args?: never): Promise<unknown /* SmbShare */[]>;

/** invoke('list_smb_shares') */
declare function invoke(cmd: 'list_smb_shares', args: { server: string, username: string | null, password: string | null }): Promise<string[]>;

/** invoke('list_usb_drives') */
declare function invoke(cmd: 'list_usb_drives', args?: never): Promise<unknown /* (String, String, u64) */[]>;

/** invoke('write_iso_to_usb') */
declare function invoke(cmd: 'write_iso_to_usb', args: { iso_path: string, device: string }): Promise<void>;

/** invoke('mount_dmg') */
declare function invoke(cmd: 'mount_dmg', args: { path: string }): Promise<string>;

/** invoke('unmount_dmg') */
declare function invoke(cmd: 'unmount_dmg', args: { loop_dev: string }): Promise<void>;

/** invoke('get_dmg_loop_device') */
declare function invoke(cmd: 'get_dmg_loop_device', args: { dmg_path: string }): Promise<string>;

/** invoke('mount_webdav') */
declare function invoke(cmd: 'mount_webdav', args: { name: string, url: string, username: string | null, password: string | null }): Promise<string>;

/** invoke('unmount_cloud') */
declare function invoke(cmd: 'unmount_cloud', args: { cloud_id: string }): Promise<void>;

/** invoke('get_cloud_mounts') */
declare function invoke(cmd: 'get_cloud_mounts', args?: never): Promise<unknown /* CloudMount */[]>;

/** invoke('scan_icon_folder') */
declare function invoke(cmd: 'scan_icon_folder', args: { folder_path: string }): Promise<unknown /* IconHit */[]>;

/** invoke('check_rclone') */
declare function invoke(cmd: 'check_rclone', args?: never): Promise<string>;

/** invoke('list_rclone_remotes') */
declare function invoke(cmd: 'list_rclone_remotes', args?: never): Promise<unknown /* CloudProviderMount */[]>;

/** invoke('add_cloud_provider') */
declare function invoke(cmd: 'add_cloud_provider', args: { provider: string, label: string }): Promise<string>;

/** invoke('mount_cloud_provider') */
declare function invoke(cmd: 'mount_cloud_provider', args: { remote_name: string }): Promise<string>;

/** invoke('unmount_cloud_provider') */
declare function invoke(cmd: 'unmount_cloud_provider', args: { remote_name: string }): Promise<void>;

/** invoke('remove_cloud_provider') */
declare function invoke(cmd: 'remove_cloud_provider', args: { remote_name: string }): Promise<void>;

/** invoke('restore_cloud_mounts') */
declare function invoke(cmd: 'restore_cloud_mounts', args?: never): Promise<string[]>;

/** invoke('find_git_root') */
declare function invoke(cmd: 'find_git_root', args: { path: string }): Promise<string | null>;

/** invoke('get_git_status') */
declare function invoke(cmd: 'get_git_status', args: { path: string }): Promise<unknown /* GitStatus */ | null>;

/** invoke('invalidate_git_cache') */
declare function invoke(cmd: 'invalidate_git_cache', args: { path: string }): Promise<void>;

/** invoke('check_gocryptfs') */
declare function invoke(cmd: 'check_gocryptfs', args?: never): Promise<string>;

/** invoke('list_vaults') */
declare function invoke(cmd: 'list_vaults', args?: never): Promise<unknown /* VaultEntry */[]>;

/** invoke('create_vault') */
declare function invoke(cmd: 'create_vault', args: { name: string, encrypted_dir: string, password: string }): Promise<unknown /* VaultEntry */>;

/** invoke('unlock_vault') */
declare function invoke(cmd: 'unlock_vault', args: { vault_id: string, password: string }): Promise<string>;

/** invoke('lock_vault') */
declare function invoke(cmd: 'lock_vault', args: { vault_id: string }): Promise<void>;

/** invoke('remove_vault') */
declare function invoke(cmd: 'remove_vault', args: { vault_id: string }): Promise<void>;

/** invoke('watch_dir') */
declare function invoke(cmd: 'watch_dir', args: { paths: string[] }): Promise<void>;

/** invoke('unwatch_dir') */
declare function invoke(cmd: 'unwatch_dir', args?: never): Promise<void>;

/** invoke('get_watch_mode') */
declare function invoke(cmd: 'get_watch_mode', args?: never): Promise<string>;

/** invoke('append_error_log') */
declare function invoke(cmd: 'append_error_log', args: { message: string }): Promise<void>;

/** invoke('get_error_log') */
declare function invoke(cmd: 'get_error_log', args?: never): Promise<string>;

/** invoke('clear_error_log') */
declare function invoke(cmd: 'clear_error_log', args?: never): Promise<void>;

/** invoke('get_file_checksums') */
declare function invoke(cmd: 'get_file_checksums', args: { path: string }): Promise<unknown>;

/** invoke('get_file_meta_exif') */
declare function invoke(cmd: 'get_file_meta_exif', args: { path: string }): Promise<unknown>;

/** invoke('write_file_meta_exif') */
declare function invoke(cmd: 'write_file_meta_exif', args: { path: string, fields: unknown /* [String; 2] */[] }): Promise<void>;

/** invoke('get_audio_tags') */
declare function invoke(cmd: 'get_audio_tags', args: { path: string }): Promise<unknown /* AudioTags */>;

/** invoke('write_audio_tags') */
declare function invoke(cmd: 'write_audio_tags', args: { path: string, tags: unknown /* AudioTags */ }): Promise<void>;

/** invoke('get_exif_tags') */
declare function invoke(cmd: 'get_exif_tags', args: { path: string }): Promise<unknown /* ExifData */>;

/** invoke('write_exif_tags') */
declare function invoke(cmd: 'write_exif_tags', args: { path: string, fields: unknown /* [String; 2][] */ }): Promise<void>;

/** invoke('get_pdf_meta') */
declare function invoke(cmd: 'get_pdf_meta', args: { path: string }): Promise<unknown /* PdfMeta */>;

/** invoke('write_pdf_meta') */
declare function invoke(cmd: 'write_pdf_meta', args: { path: string, fields: unknown /* [String; 2][] */ }): Promise<void>;

/** invoke('compare_dirs') */
declare function invoke(cmd: 'compare_dirs', args: { path_left: string, path_right: string }): Promise<unknown /* DirDiffResult */>;

/** invoke('sync_folders_preview') */
declare function invoke(cmd: 'sync_folders_preview', args: { left: string, right: string }): Promise<unknown /* SyncPreview */>;

/** invoke('sync_folders') */
declare function invoke(cmd: 'sync_folders', args: { left: string, right: string, delete_orphans: boolean }): Promise<unknown /* SyncResult */>;

/** invoke('create_version') */
declare function invoke(cmd: 'create_version', args: { path: string, note?: string }): Promise<unknown /* FileVersion */>;

/** invoke('list_versions') */
declare function invoke(cmd: 'list_versions', args: { path: string }): Promise<unknown /* FileVersion */[]>;

/** invoke('restore_version') */
declare function invoke(cmd: 'restore_version', args: { path: string, version_id: string }): Promise<string>;

/** invoke('delete_version') */
declare function invoke(cmd: 'delete_version', args: { path: string, version_id: string }): Promise<void>;

/** invoke('prune_versions') */
declare function invoke(cmd: 'prune_versions', args: { path: string, keep_last?: number }): Promise<number>;

/** invoke('get_version_stats') */
declare function invoke(cmd: 'get_version_stats', args?: never): Promise<{ total_versions: number; total_size: number; files_with_versions: number }>;

/** invoke('generate_signing_key') */
declare function invoke(cmd: 'generate_signing_key', args?: never): Promise<{ public_key: string; created_at: number }>;

/** invoke('get_signing_key') */
declare function invoke(cmd: 'get_signing_key', args?: never): Promise<{ public_key: string; created_at: number } | null>;

/** invoke('sign_file') */
declare function invoke(cmd: 'sign_file', args: { path: string }): Promise<string>;

/** invoke('verify_signature') */
declare function invoke(cmd: 'verify_signature', args: { path: string, signature: string, public_key: string }): Promise<boolean>;

/** invoke('delete_signing_key') */
declare function invoke(cmd: 'delete_signing_key', args?: never): Promise<void>;

/** invoke('mount_sftp') */
declare function invoke(cmd: 'mount_sftp', args: { host: string, port: number, username: string, password: string, key_path: string, remote_path: string }): Promise<string>;

/** invoke('unmount_sftp') */
declare function invoke(cmd: 'unmount_sftp', args: { id: string }): Promise<void>;

/** invoke('get_sftp_mounts') */
declare function invoke(cmd: 'get_sftp_mounts', args?: never): Promise<unknown /* SftpMount */[]>;

/** invoke('mount_ftp') */
declare function invoke(cmd: 'mount_ftp', args: { host: string, port: number, username: string, password: string, remote_path: string, passive: boolean, tls: boolean }): Promise<string>;

/** invoke('unmount_ftp') */
declare function invoke(cmd: 'unmount_ftp', args: { id: string }): Promise<void>;

/** invoke('get_ftp_mounts') */
declare function invoke(cmd: 'get_ftp_mounts', args?: never): Promise<unknown /* FtpMount */[]>;

/** invoke('get_file_permissions') */
declare function invoke(cmd: 'get_file_permissions', args: { path: string }): Promise<unknown /* FilePermissionsInfo */>;

/** invoke('chmod_entry') */
declare function invoke(cmd: 'chmod_entry', args: { path: string, mode: number }): Promise<void>;

/** invoke('chown_entry') */
declare function invoke(cmd: 'chown_entry', args: { path: string, owner: string, group: string }): Promise<void>;

/** invoke('open_new_window') */
declare function invoke(cmd: 'open_new_window', args: { path: string }): Promise<void>;

/** invoke('scan_dir_sizes') */
declare function invoke(cmd: 'scan_dir_sizes', args: { path: string }): Promise<unknown /* DirSizeEntry */[]>;

/** invoke('probe_video_codec') */
declare function invoke(cmd: 'probe_video_codec', args: { path: string }): Promise<unknown /* VideoCodecInfo */ | null>;

/** invoke('load_plugins') */
declare function invoke(cmd: 'load_plugins', args?: never): Promise<unknown /* PluginDef */[]>;

/** invoke('save_plugins') */
declare function invoke(cmd: 'save_plugins', args: { plugins: unknown /* PluginDef */[] }): Promise<void>;

/** invoke('check_plugin_trust') */
declare function invoke(cmd: 'check_plugin_trust', args: { plugin_id: string, command: string }): Promise<unknown>;

/** invoke('approve_plugin') */
declare function invoke(cmd: 'approve_plugin', args: { plugin_id: string, command: string }): Promise<void>;

/** invoke('revoke_plugin_trust') */
declare function invoke(cmd: 'revoke_plugin_trust', args: { plugin_id: string }): Promise<void>;

/** invoke('run_plugin_command') */
declare function invoke(cmd: 'run_plugin_command', args: { command: string, work_dir: string }): Promise<unknown /* PluginResult */>;

/** invoke('save_undo_history') */
declare function invoke(cmd: 'save_undo_history', args: { history: unknown }): Promise<void>;

/** invoke('load_undo_history') */
declare function invoke(cmd: 'load_undo_history', args?: never): Promise<unknown>;

/** invoke('clear_undo_history') */
declare function invoke(cmd: 'clear_undo_history', args?: never): Promise<void>;

/** invoke('get_cloud_sync_state') */
declare function invoke(cmd: 'get_cloud_sync_state', args: { local_dir: string, cloud_remote: string }): Promise<unknown /* FileSyncState */[]>;

/** invoke('check_cloud_remote_reachable') */
declare function invoke(cmd: 'check_cloud_remote_reachable', args: { cloud_remote: string }): Promise<boolean>;

/** invoke('start_rclone_rc') */
declare function invoke(cmd: 'start_rclone_rc', args?: never): Promise<string>;

/** invoke('stop_rclone_rc') */
declare function invoke(cmd: 'stop_rclone_rc', args?: never): Promise<void>;

/** invoke('rclone_rc_list') */
declare function invoke(cmd: 'rclone_rc_list', args: { remote: string, path: string }): Promise<unknown[]>;

/** invoke('rclone_rc_copy') */
declare function invoke(cmd: 'rclone_rc_copy', args: { src_fs: string, src_path: string, dst_fs: string, dst_path: string }): Promise<void>;

/** invoke('detect_mtp_devices') */
declare function invoke(cmd: 'detect_mtp_devices', args?: never): Promise<unknown /* MtpDevice */[]>;

/** invoke('mount_mtp') */
declare function invoke(cmd: 'mount_mtp', args: { device_id: string }): Promise<string>;

/** invoke('unmount_mtp') */
declare function invoke(cmd: 'unmount_mtp', args: { device_id: string }): Promise<void>;

/** invoke('get_settings') */
declare function invoke(cmd: 'get_settings', args?: never): Promise<unknown>;

/** invoke('set_settings') */
declare function invoke(cmd: 'set_settings', args: { settings: unknown }): Promise<void>;

/** invoke('split_file') */
declare function invoke(cmd: 'split_file', args: { path: string, chunk_size: number }): Promise<string[]>;

/** invoke('join_files') */
declare function invoke(cmd: 'join_files', args: { paths: string[], output_path: string }): Promise<number>;

/** invoke('encrypt_file') */
declare function invoke(cmd: 'encrypt_file', args: { path: string, password: string }): Promise<string>;

/** invoke('decrypt_file') */
declare function invoke(cmd: 'decrypt_file', args: { path: string, password: string }): Promise<string>;

/** invoke('set_file_comment') */
declare function invoke(cmd: 'set_file_comment', args: { path: string, comment: string }): Promise<void>;

/** invoke('get_file_comment') */
declare function invoke(cmd: 'get_file_comment', args: { path: string }): Promise<string | null>;

/** invoke('get_all_comments') */
declare function invoke(cmd: 'get_all_comments', args?: never): Promise<Record<string, string>>;

export {};